### ISSUE TITLE
The minimum supported version of win10 is Windows 10 Build 20348

### ISSUE THREAD

**Issue by z0j** [samuelgr/Pathwinder#1]
This content fits what I need perfectly. However, I keep getting an error when I start it: unable to locate program input point GetTempPath2W with dynamic link library.
After tough troubleshooting, I finally realized that this function has system requirements, the minimum required system is Windows 10 Build 20348, which is described in this place: https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi- gettemppath2w.
This thing is too important for me, can it be adapted to an earlier version? For example like my system version window 10 Build 19045?
Thank you very much!

Translated with DeepL.com (free version)

**Comment by samuelgr** [comment]
Apologies, I didn't intend to make Pathwinder only work with Windows 11. I changed to the older API in 7d5c4e5da43bd58cad7a909238346061ac2ea43c.
